/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author saera
 */
public class modul8 extends javax.swing.JFrame {

    /**
     * Creates new form modul8
     */
    public modul8() {
        initComponents();
        addModulToTab();
    }
    
    private void addModulToTab() {
        // Buat instance dari modul yang sudah ada
        modul1 frame1 = new modul1();
        modul2 frame2 = new modul2();
        modul3 frame3 = new modul3();
        modul4 frame4 = new modul4();
        modul5 frame5 = new modul5();
        
        // Extract content from each JFrame and add to JPanel
        Pertama.setLayout(new BorderLayout());
        Pertama.add(frame1.getContentPane(), BorderLayout.CENTER);

        Kedua.setLayout(new BorderLayout());
        Kedua.add(frame2.getContentPane(), BorderLayout.CENTER);

        Ketiga.setLayout(new BorderLayout());
        Ketiga.add(frame3.getContentPane(), BorderLayout.CENTER);

        Keempat.setLayout(new BorderLayout());
        Keempat.add(frame4.getContentPane(), BorderLayout.CENTER);

        Kelima.setLayout(new BorderLayout());
        Kelima.add(frame5.getContentPane(), BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Pertama = new javax.swing.JPanel();
        Kedua = new javax.swing.JPanel();
        Ketiga = new javax.swing.JPanel();
        Keempat = new javax.swing.JPanel();
        Kelima = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PertamaLayout = new javax.swing.GroupLayout(Pertama);
        Pertama.setLayout(PertamaLayout);
        PertamaLayout.setHorizontalGroup(
            PertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        PertamaLayout.setVerticalGroup(
            PertamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pertama", Pertama);

        javax.swing.GroupLayout KeduaLayout = new javax.swing.GroupLayout(Kedua);
        Kedua.setLayout(KeduaLayout);
        KeduaLayout.setHorizontalGroup(
            KeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        KeduaLayout.setVerticalGroup(
            KeduaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kedua", Kedua);

        javax.swing.GroupLayout KetigaLayout = new javax.swing.GroupLayout(Ketiga);
        Ketiga.setLayout(KetigaLayout);
        KetigaLayout.setHorizontalGroup(
            KetigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        KetigaLayout.setVerticalGroup(
            KetigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ketiga", Ketiga);

        javax.swing.GroupLayout KeempatLayout = new javax.swing.GroupLayout(Keempat);
        Keempat.setLayout(KeempatLayout);
        KeempatLayout.setHorizontalGroup(
            KeempatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        KeempatLayout.setVerticalGroup(
            KeempatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Keempat", Keempat);

        javax.swing.GroupLayout KelimaLayout = new javax.swing.GroupLayout(Kelima);
        Kelima.setLayout(KelimaLayout);
        KelimaLayout.setHorizontalGroup(
            KelimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        KelimaLayout.setVerticalGroup(
            KelimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kelima", Kelima);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Kedua;
    private javax.swing.JPanel Keempat;
    private javax.swing.JPanel Kelima;
    private javax.swing.JPanel Ketiga;
    private javax.swing.JPanel Pertama;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
