/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas;

import tugas.koneksi;
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.*;
import java.time.Clock;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saera
 */
public class modul13 extends javax.swing.JFrame {

    /**
     * Creates new form modul13
     */
    public modul13() {
        initComponents();
        tampildata();
        bersih();
    }

    public void bersih() {
        eNama.setText("");
        eJeniskel.setText("");
        eCari.setText("");
        cbSpesialis.setSelectedItem(0);
    }

    public void tampildata() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Nama");
        tbl.addColumn("Jenis Kelamin");
        tbl.addColumn("Spesialis");
        tblDokter.setModel(tbl);

        try {
            Connection conn = koneksi.GetConnection(); // Get the connection from koneksi class
            Statement statement = conn.createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM dokter");
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("nama"),
                    res.getString("jenis_kelamin"),
                    res.getString("spesialis"),
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        eJeniskel = new javax.swing.JTextField();
        cbSpesialis = new javax.swing.JComboBox<>();
        bSimpan = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        eCari = new javax.swing.JTextField();
        tblDokter = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Jenis Kelamin");

        jLabel3.setText("Spesialis");

        eNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNamaActionPerformed(evt);
            }
        });

        cbSpesialis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokter Umum", "Penyakit Dalam", "Anak", "Kandungan", "Bedah", "Jantung", "Gigi", "Saraf", "Kulit", "Mata" }));

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bKeluar.setText("Keluar");

        jLabel4.setText("Cari");

        eCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCariActionPerformed(evt);
            }
        });

        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDokterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eJeniskel)
                            .addComponent(eNama)
                            .addComponent(cbSpesialis, 0, 199, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(eCari))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bSimpan)
                            .addGap(18, 18, 18)
                            .addComponent(bEdit)
                            .addGap(18, 18, 18)
                            .addComponent(bHapus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bKeluar))))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tblDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eJeniskel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan)
                    .addComponent(bEdit)
                    .addComponent(bHapus)
                    .addComponent(bKeluar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(eCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(423, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tblDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNamaActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        try { 
            Statement statement = (Statement) 
            koneksi.GetConnection().createStatement(); 
            statement.executeUpdate("insert into dokter values ('"+eNama.getText()+"','"+eJeniskel.getText()+"','"+cbSpesialis.getSelectedItem()+"');"); 
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan"); 
            tampildata(); 
            bersih(); 
        }catch (Exception t){ 
            JOptionPane.showMessageDialog(null, "Data gagal disimpan"); 
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        try { 
        Statement statement = (Statement) 
        koneksi.GetConnection().createStatement(); 
        statement.executeUpdate("UPDATE dokter SET jenis_kelamin = '"+eJeniskel.getText()+"', spesialis = '"+cbSpesialis.getSelectedItem()+"' WHERE nama = '"+eNama.getText()+"';"); 
        statement.close(); 
        JOptionPane.showMessageDialog(null, "Data berhasil Dirubah"); 
        tampildata(); 
        bersih(); 
    }catch (Exception t){ 
        JOptionPane.showMessageDialog(null, "Data gagal Dirubah: " + t.getMessage()); 
    }
    }//GEN-LAST:event_bEditActionPerformed

    private void eCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCariActionPerformed
        // TODO add your handling code here:
        String cari = eCari.getText(); 
        DefaultTableModel tbl = new DefaultTableModel(); 
        tbl.addColumn("NIM"); 
        tbl.addColumn("Nama"); 
        tbl.addColumn("Jurusan"); 
        tblDokter.setModel(tbl); 
        try { 
            Statement statement = (Statement) 
            koneksi.GetConnection().createStatement(); 
            ResultSet res = statement.executeQuery("select * from dokter where nama like '%" + cari + "%'" + "or jenis_kelamin like '%" + cari + "%';"); 
            while (res.next()){ 
                tbl.addRow(new Object[] { 
                    res.getString("nama"), 
                    res.getString("jenis_kelamin"), 
                    res.getString("spesialis"), 
                }); 
                tblDokter.setModel(tbl); 
                bersih(); 
                } 
        }catch (Exception e){ 
            JOptionPane.showMessageDialog(rootPane, "salah"); 
        } 
    }//GEN-LAST:event_eCariActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        String nama = eNama.getText(); 
        try { 
            Statement statement = (Statement) 
            koneksi.GetConnection().createStatement(); 
            statement.executeUpdate("delete from dokter where nama= ('"+nama+"');"); 
            tampildata(); 
            bersih(); 
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus"); 
        }catch (Exception t) { 
            JOptionPane.showMessageDialog(null, "Data gaagl dihapus"); 
        } 
    }//GEN-LAST:event_bHapusActionPerformed

    private void tblDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDokterMouseClicked
        // TODO add your handling code here:
        int row = tblDokter.getSelectedRow(); 
        eNama.setText((String)tblDokter.getValueAt(row, 0)); 
        eJeniskel.setText((String)tblDokter.getValueAt(row, 1));       
        cbSpesialis.setSelectedItem((String)tblDokter.getValueAt(row, 2)); 
    }//GEN-LAST:event_tblDokterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JComboBox<String> cbSpesialis;
    private javax.swing.JTextField eCari;
    private javax.swing.JTextField eJeniskel;
    private javax.swing.JTextField eNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTable tblDokter;
    // End of variables declaration//GEN-END:variables
}
