/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas;

/**
 *
 * @author saera
 */
public class modul10 extends javax.swing.JFrame {

    /**
     * Creates new form modul10
     */
    public modul10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        eHasil = new javax.swing.JTextField();
        JmenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        menProses = new javax.swing.JMenu();
        menPersegipanjang = new javax.swing.JMenu();
        meltLuaspersegip = new javax.swing.JMenuItem();
        meltKelilingpersegip = new javax.swing.JMenuItem();
        menSegitiga = new javax.swing.JMenu();
        meltLuassegitiga = new javax.swing.JMenuItem();
        meltKelilingsegitiga = new javax.swing.JMenuItem();
        menLingkaran = new javax.swing.JMenu();
        meltLuaslingkaran = new javax.swing.JMenuItem();
        meltKelilinglingkaran = new javax.swing.JMenuItem();
        menBantuan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Panjang / Alas / Jari-jari");

        jLabel2.setText("Lebar/ Tinggi");

        jLabel3.setText("Hasil");

        eData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eData1ActionPerformed(evt);
            }
        });

        menFile.setText("File");
        JmenuBar1.add(menFile);

        menProses.setText("Proses");

        menPersegipanjang.setText("Persegi Panjang");

        meltLuaspersegip.setText("Luas");
        meltLuaspersegip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuaspersegipActionPerformed(evt);
            }
        });
        menPersegipanjang.add(meltLuaspersegip);

        meltKelilingpersegip.setText("Keliling");
        meltKelilingpersegip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilingpersegipActionPerformed(evt);
            }
        });
        menPersegipanjang.add(meltKelilingpersegip);

        menProses.add(menPersegipanjang);

        menSegitiga.setText("Segitiga");

        meltLuassegitiga.setText("Luas");
        meltLuassegitiga.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltLuassegitigaStateChanged(evt);
            }
        });
        meltLuassegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuassegitigaActionPerformed(evt);
            }
        });
        menSegitiga.add(meltLuassegitiga);

        meltKelilingsegitiga.setText("Keliling");
        meltKelilingsegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilingsegitigaActionPerformed(evt);
            }
        });
        menSegitiga.add(meltKelilingsegitiga);

        menProses.add(menSegitiga);

        menLingkaran.setText("Lingkaran");

        meltLuaslingkaran.setText("Luas");
        meltLuaslingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuaslingkaranActionPerformed(evt);
            }
        });
        menLingkaran.add(meltLuaslingkaran);

        meltKelilinglingkaran.setText("Keliling");
        meltKelilinglingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilinglingkaranActionPerformed(evt);
            }
        });
        menLingkaran.add(meltKelilinglingkaran);

        menProses.add(menLingkaran);

        JmenuBar1.add(menProses);

        menBantuan.setText("Bantuan");
        JmenuBar1.add(menBantuan);

        setJMenuBar(JmenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eData1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eData1ActionPerformed

    private void meltLuaspersegipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuaspersegipActionPerformed
        // TODO add your handling code here:
        double panjang = Double.parseDouble(eData1.getText());
        double lebar = Double.parseDouble(eData2.getText());
        double luas = panjang * lebar;
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuaspersegipActionPerformed

    private void meltKelilingpersegipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilingpersegipActionPerformed
        // TODO add your handling code here:
        double panjang = Double.parseDouble(eData1.getText());
        double lebar = Double.parseDouble(eData2.getText());
        double keliling = 2 * (panjang + lebar);
        eHasil.setText(String.valueOf(keliling));
    }//GEN-LAST:event_meltKelilingpersegipActionPerformed

    private void meltLuassegitigaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltLuassegitigaStateChanged
        // TODO add your handling code here:
        double alas = Double.parseDouble(eData1.getText());
        double tinggi = Double.parseDouble(eData2.getText());
        double luas = 0.5 * alas * tinggi;
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuassegitigaStateChanged

    private void meltKelilingsegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilingsegitigaActionPerformed
        // TODO add your handling code here:
        double alas = Double.parseDouble(eData1.getText());
        double tinggi = Double.parseDouble(eData2.getText());
        double sisiMiring = Math.sqrt(alas * alas + tinggi * tinggi);
        double keliling = alas + tinggi + sisiMiring;
        eHasil.setText(String.valueOf(keliling));
    }//GEN-LAST:event_meltKelilingsegitigaActionPerformed

    private void meltLuassegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuassegitigaActionPerformed
        // TODO add your handling code here:
        double alas = Double.parseDouble(eData1.getText());
        double tinggi = Double.parseDouble(eData2.getText());
        double luas = 0.5 * alas * tinggi;
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuassegitigaActionPerformed

    private void meltLuaslingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuaslingkaranActionPerformed
        // TODO add your handling code here:
        double radius = Double.parseDouble(eData1.getText());
        double luas = Math.PI * radius * radius;
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuaslingkaranActionPerformed

    private void meltKelilinglingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilinglingkaranActionPerformed
        // TODO add your handling code here:
        double radius = Double.parseDouble(eData1.getText());
        double keliling = 2 * Math.PI * radius;
        eHasil.setText(String.valueOf(keliling));
    }//GEN-LAST:event_meltKelilinglingkaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JmenuBar1;
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eHasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem meltKelilinglingkaran;
    private javax.swing.JMenuItem meltKelilingpersegip;
    private javax.swing.JMenuItem meltKelilingsegitiga;
    private javax.swing.JMenuItem meltLuaslingkaran;
    private javax.swing.JMenuItem meltLuaspersegip;
    private javax.swing.JMenuItem meltLuassegitiga;
    private javax.swing.JMenu menBantuan;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menLingkaran;
    private javax.swing.JMenu menPersegipanjang;
    private javax.swing.JMenu menProses;
    private javax.swing.JMenu menSegitiga;
    // End of variables declaration//GEN-END:variables
}
